// This header file was auto-generated by ClassMate++
// Created: 12 Nov 2014 8:23:49 pm
// Copyright (c) 2014, HurleyWorks

#pragma once

#include "PhysicsDefaults.h"

struct BodyDesc
{
	BodyDesc ();
	~BodyDesc() = default;

	void setToDefault();

	BodyType bodyType;
	CollisionShape shape;
	FlexType flex;
	float mass;
	ci::vec3 force;
	std::string name;
	ci::Color color;

}; // end class BodyDesc
