
// This header file was auto-generated by ClassMate++
// Created: 26 Apr 2015 8:48:48 am
// Copyright (c) 2015, HurleyWorks

#pragma  once

#include "PhysicsData.h"

class BodyState
{

 public:
	BodyState() = default;
	~BodyState() = default;

	bool isPickable() const { return (state_ & PBodyState::SeenByMouseRay) == PBodyState::SeenByMouseRay; }
	bool isInEngine() const { return (state_ & PBodyState::InEngine) == PBodyState::InEngine; }
	bool isBeingProcessed() const { return (state_ & PBodyState::BeingProcessed) == PBodyState::BeingProcessed; }
	bool isEmitted() const { return (state_ & PBodyState::HasImpulseApplied) == PBodyState::HasImpulseApplied; }
	bool isDeleted() const { return (state_ & PBodyState::Deleted) == PBodyState::Deleted; }
	bool isRecycled() const { return (state_ & PBodyState::Recycled) == PBodyState::Recycled; }
	bool isReady() const { return (isBeingProcessed() || 
								   isDeleted() ||
								   isRecycled() ||
		                           !isInEngine()) ? false : true; }

	PBodyState & getState() { return state_; }

 private:
	 PBodyState state_ = 0;

}; // end class PhysicsBodyState
