// This source file was auto-generated by ClassMate++
// Created: 12 Nov 2014 8:23:49 pm
// Copyright (c) 2014, HurleyWorks

#include "BodyDesc.h"

using namespace ci;

// ctor
BodyDesc::BodyDesc ()
{	
	setToDefault();
}

void BodyDesc::setToDefault()
{
	color = DEFAULT_COLOR;
	bodyType = DEFAULT_BODYTYPE;
	shape = DEFAULT_SHAPE;
	flex = DEFAULT_FLEX;
	mass = DEFAULT_DYNAMIC_MASS;
	force = DEFAULT_GRAVITY;
	name = DEFAULT_BODY_NAME;
}