// This header file was auto-generated by ClassMate++
// Created: 27 Apr 2015 8:38:20 pm
// Copyright (c) 2015, HurleyWorks

#pragma  once

#include "../../../NewtonAPI.h"

struct Entity
{
	static void transformCallback(const NewtonBody * newtonBody,
								  const dFloat * matrix,
								  int threadIndex);

	static void applyForceAndTorqueCallback(const NewtonBody * newtonBody,
											dFloat timestep,
											int threadIndex);
	
	static void destroyBodyCallback(const NewtonBody * newtonBody);

}; // end class Entity
