// This source file was auto-generated by ClassMate++
// Created: 12 Jan 2013 8:42:22 am
// Copyright (c) 2013, HurleyWorks;

#include "Listeners.h"
#include "PhysicsScene.h"

// ctor
ListenerBase::ListenerBase (PhysicsScene * const scene,
							const char * const listenerName)
{	
	NewtonWorldAddPreListener (scene->getWorld(), listenerName, this, preUpdate, nullptr);
	NewtonWorldAddPostListener (scene->getWorld(), listenerName, this, postUpdate, destroy);
}

// destroy
void ListenerBase::destroy (const NewtonWorld * const world,
                            void * const listenerUserData)
{	
	ListenerBase* const me = (ListenerBase*) listenerUserData;
	delete me;
}

// postUpdate
void ListenerBase::postUpdate(const NewtonWorld * const world, 
									void * const listenerUserData,
									dFloat timeStep)
{

	ListenerBase* const me = (ListenerBase*) listenerUserData;
	me->postUpdate(world, timeStep);
}

// preUpdate
void ListenerBase::preUpdate (const NewtonWorld * const world,
                                    void * const listenerUserData, 
                                    dFloat timeStep)
{	
	ListenerBase* const me = (ListenerBase*) listenerUserData;
	me->preUpdate(world, timeStep);
}


// ------------------------------- AppListener
// ctor
AppListener::AppListener (PhysicsScene * const scene)
	: ListenerBase(scene, "App Listener"),
	  scene_(scene), 
	  postPhysicsCallback_(nullptr),
	  prePhysicsCallback_(nullptr)
{	
}

// postUpdate
void AppListener::postUpdate (const NewtonWorld * const world, dFloat timeStep)
{	
	postPhysicsCallback_(scene_, timeStep);
}

// preUpdate
void AppListener::preUpdate (const NewtonWorld * const world, dFloat timeStep)
{	
	prePhysicsCallback_(scene_, timeStep);
}
