// This source file was auto-generated by ClassMate++
// Created: 5 Nov 2015 9:23:18 am
// Copyright (c) 2015, HurleyWorks

#include "PhysicsEngine.h"

// ctor
PhysicsEngine::PhysicsEngine (NewtonWorld * const world)
	: world(world)
{	
}

void PhysicsEngine::advancePhysics()
{
	if (db){__debugbreak();}

	for (unsigned int i = 0; i < substeps_; i++)
	{
		NewtonUpdate(world, timeStep_);
	}
}

