// This header file was auto-generated by ClassMate++
// Created: 12 Jan 2013 8:17:38 am
// Copyright (c) 2013, HurleyWorks

#pragma  once

#include "../../../NewtonAPI.h"
#include <cinder/Vector.h>

struct Pick
{
	Pick ();
	~Pick() = default;

	static dFloat RayCastFilter ( const NewtonBody* const body, 
								  const NewtonCollision* const collisionHit, 
								  const dFloat* const contact,
								  const dFloat* const normal,
								  dLong collisionID, 
								  void* const userData,
								  dFloat intersetParam);

	static unsigned RayCastPrefilter (const NewtonBody * body,
                                      const NewtonCollision * const collision, 
                                      void * const userData);

	dFloat param_;
	const NewtonBody * body_;
	ci::vec3 normal_;

}; // end class Pick
