// This header file was auto-generated by ClassMate++
// Created: 26 Apr 2015 8:25:05 am
// Copyright (c) 2015, HurleyWorks

#pragma once

#include <chrono>
#include "cinder/Vector.h"
#include "cinder/Matrix.h"
#include "cinder/AxisAlignedBox.h"

struct SpaceTime
{
	SpaceTime ();
	~SpaceTime() = default;

	void reset();
	void updateWorldBounds();

	std::chrono::duration<double> getLifeSpan();

	ci::vec3 scale;

	ci::mat4 startTransform;
	ci::mat4 localTransform;
	ci::mat4 worldTransform;

	ci::AxisAlignedBox modelBound;
	ci::AxisAlignedBox worldBound;

	std::chrono::time_point<std::chrono::system_clock> birth;

	// emitted
	float speed;
	ci::vec3 direction;

}; // end class SpaceTime
