 // This source file was auto-generated by ClassMate++
// Created: 5 Nov 2015 6:10:39 pm
// Copyright (c) 2015, HurleyWorks

#include "ActiveDispatcher.h"

int ActiveDispatcher::dispatchBody(PhysicsBodyRef & pBody, PhysicsSceneRef & scene, const EngineState engineState)
{
	if (!pBody || !scene) return 0;

	try
	{
		// we're about to be processed by the physics engine
		pBody->state.getState() |= PBodyState::BeingProcessed;

		scene->processPhysicsBody(pBody, engineState);
	}
	catch (std::exception & )
	{
	
	}
	catch (...)
	{
		
	}

	return 0;
}


