// This source file was auto-generated by ClassMate++
// Created: 5 Nov 2015 6:10:39 pm
// Copyright (c) 2015, HurleyWorks

#include "ActiveDispatcher.h"

// ctor
ActiveDispatcher::ActiveDispatcher ()
{	
}

// dtor
ActiveDispatcher::~ActiveDispatcher ()
{	
}

int ActiveDispatcher::dispatchBody(PhysicsBodyRef & pBody, PhysicsSceneRef & scene)
{
	if (!pBody || !scene) return 0;

	try
	{
		// we're about to processed by the physics engine
		pBody->state.getState() |= PBodyState::BeingProcessed;

		scene->processPhysicsBody(pBody);
	}
	catch (std::exception & e)
	{
	
	}
	catch (...)
	{
		
	}

	return 0;
}


