// This source file was auto-generated by ClassMate++
// Created: 30 Apr 2015 7:49:12 am
// Copyright (c) 2015, HurleyWorks

#include "MeshOps.h"

using namespace ci;

void MeshOps::centerVertices(TriMeshRef & mesh)
{
	AxisAlignedBox modelBound = mesh->calcBoundingBox();
	vec3 offset = modelBound.getCenter();

	// need an approxiamtely equal here. Does glm have one?
	if ( offset == vec3(0.0f)) return;

	int pointCount = mesh->getNumVertices();
	vec3 * positions = mesh->getPositions<3>();

	for (int i = 0; i < pointCount; i++)
		positions[i] -= offset;

	// recalc the bounding box later
}

