// This header file was auto-generated by ClassMate++
// Created: 30 Apr 2015 7:49:12 am
// Copyright (c) 2015, HurleyWorks

#pragma once

#include <cinder/TriMesh.h>

class MeshOps
{
   public:
      MeshOps() = default;
      ~MeshOps() = default;

      void centerVertices (ci::TriMeshRef & mesh);

}; // end class MeshOps
